### ISSUE TITLE
Error when running Experiment.py

### ISSUE THREAD

**Issue by laochonlam** [AmedeoSapio/DAIET-HotNets17#2]
Hi,
I am trying to reproduce the experiment from the published paper and followed the instructions from `README.md` ,

9. Start the testbed:
```
wd=`pwd`
cd DAIET/tests/single_switch/
./Experiment.py ${wd}
```

and then I got the error
```
Traceback (most recent call last):
  File "./Experiment.py", line 154, in <module>
    exp.run()
  File "./Experiment.py", line 59, in run
    pid = int(self.run_cmd("docker inspect --format '{{.State.Pid}}' h"+str(i)))
ValueError: invalid literal for int() with base 10: '\x1b[91m\x1b[0m'
```
I have tried ubuntu16.04 and 14.04 but two machines got the same error.

any ideas? Appreciated your help.

**Comment by laochonlam** [comment]
Seems I forgot to change `--cpuset-cpus` option
